server:
  port: 9000


# expose all metrics
management:
  endpoints:
    web:
      exposure:
        include: health

spring:

#  database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/arigrow


# flyway
  flyway:
    enabled: true
    user: postgres
    password: postgres
    schemas: public
    url: jdbc:postgresql://localhost:5432/arigrow
    locations: classpath:db/migrations
    baseline-on-migrate: true

# swagger documentation
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /


